# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

gem "jekyll", "~> 4.4"

gem "jekyll-feed", "~> 0.17.0"

gem "jekyll-remote-theme", "~> 0.5.2"

gem "jekyll-seo-tag", "~> 2.9"
